### ISSUE TITLE
0.0.2beta導入でphpエラー

### ISSUE THREAD

**Issue by harmo-snipe** [megumiteam/simple-ga4-ranking#11]
Simple GA Analyticsからの移行です。
0.02

`Fatal error: Uncaught Error: Call to undefined function Google\Protobuf\Internal\bccomp() in /自分のディレクトリ/blog/wp-content/plugins/simple-ga-4-ranking/vendor/google/protobuf/src/Google/Protobuf/Internal/Message.php:959 Stack trace: #0 /自分のディレクトリ/blog/wp-content/plugins/simple-ga-4-ranking/vendor/google/protobuf/src/Google/Protobuf/Internal/Message.php(1300): Google\Protobuf\Internal\Message->convertJsonValueToProtoValue(8, Object(Google\Protobuf\Internal\FieldDescriptor), true) #1 /自分のディレクトリ/blog/wp-content/plugins/simple-ga-4-ranking/vendor/google/protobuf/src/Google/Protobuf/Internal/Message.php(1239): Google\Protobuf\Internal\Message->mergeFromArrayJsonImpl(Array, true) #2 /自分のディレクトリ/blog/wp-content/plugins/simple-ga-4-ranking/vendor/google/protobuf/src/Google/Protobuf/Internal/Message.php(1336): Google\Protobuf\Internal\Message->mergeFromJsonArray(Array, true) #3 /自分のディレクトリ/blog/wp-content/plugins/simple-ga-4-ranking/vendor/google/protobuf/src/Google/Protobuf/Internal/Message.php(793): Google\Protobuf\Internal\Message->parseFromJsonStream(Object(Google\Protobuf\Internal\RawInputStream), true) #4 /自分のディレクトリ/blog/wp-content/plugins/simple-ga-4-ranking/vendor/google/gax/src/Transport/RestTransport.php(133): Google\Protobuf\Internal\Message->mergeFromJsonString('{\n "dimensionH...', true) #5 /自分のディレクトリ/blog/wp-content/plugins/simple-ga-4-ranking/vendor/guzzlehttp/promises/src/Promise.php(204): Google\ApiCore\Transport\RestTransport->Google\ApiCore\Transport\{closure}(Object(GuzzleHttp\Psr7\Response)) #6 /自分のディレクトリ/blog/wp-content/plugins/simple-ga-4-ranking/vendor/guzzlehttp/promises/src/Promise.php(153): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), NULL) #7 /自分のディレクトリ/blog/wp-content/plugins/simple-ga-4-ranking/vendor/guzzlehttp/promises/src/TaskQueue.php(48): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}() #8 /自分のディレクトリ/blog/wp-content/plugins/simple-ga-4-ranking/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(158): GuzzleHttp\Promise\TaskQueue->run() #9 /自分のディレクトリ/blog/wp-content/plugins/simple-ga-4-ranking/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(183): GuzzleHttp\Handler\CurlMultiHandler->tick() #10 /自分のディレクトリ/blog/wp-content/plugins/simple-ga-4-ranking/vendor/guzzlehttp/promises/src/Promise.php(248): GuzzleHttp\Handler\CurlMultiHandler->execute(true) #11 /自分のディレクトリ/blog/wp-content/plugins/simple-ga-4-ranking/vendor/guzzlehttp/promises/src/Promise.php(224): GuzzleHttp\Promise\Promise->invokeWaitFn() #12 /自分のディレクトリ/blog/wp-content/plugins/simple-ga-4-ranking/vendor/guzzlehttp/promises/src/Promise.php(269): GuzzleHttp\Promise\Promise->waitIfPending() #13 /自分のディレクトリ/blog/wp-content/plugins/simple-ga-4-ranking/vendor/guzzlehttp/promises/src/Promise.php(226): GuzzleHttp\Promise\Promise->invokeWaitList() #14 /自分のディレクトリ/blog/wp-content/plugins/simple-ga-4-ranking/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending() #15 /自分のディレクトリ/blog/wp-content/plugins/simple-ga-4-ranking/vendor/google/analytics-data/src/V1beta/Gapic/BetaAnalyticsDataGapicClient.php(1076): GuzzleHttp\Promise\Promise->wait() #16 /自分のディレクトリ/blog/wp-content/plugins/simple-ga-4-ranking/includes/Analytics.php(32): Google\Analytics\Data\V1beta\Gapic\BetaAnalyticsDataGapicClient->runReport(Array) #17 /自分のディレクトリ/blog/wp-content/plugins/simple-ga-4-ranking/modules/functions.php(139): digitalcube\SimpleGA4Ranking\Analytics->fetch(Array) #18 /自分のディレクトリ/blog/wp-content/plugins/simple-ga-4-ranking/modules/functions.php(287): sga_ranking_ids(Array) #19 /自分のディレクトリ/blog/wp-content/themes/ribbon_tw/page-ranking.php(19): sga_ranking_get_date(Array) #20 /自分のディレクトリ/blog/wp-includes/template-loader.php(106): include('/自分のディレクトリ/b...') #21 /自分のディレクトリ/blog/wp-blog-header.php(19): require_once('/自分のディレクトリ/b...') #22 /自分のディレクトリ/blog/index.php(17): require('/自分のディレクトリ/b...') #23 {main} thrown in /自分のディレクトリ/blog/wp-content/plugins/simple-ga-4-ranking/vendor/google/protobuf/src/Google/Protobuf/Internal/Message.php on line 959
`

**Comment by mt8** [comment]
@harmo-snipe 
issueありがとうございます。
すでに自作中ということですが、`digitalcube\SimpleGA4Ranking\Analytics->fetch()`でエラーになっているようなので、その辺り詳しく分かるとよさそうですね。
ありがとうございました。
